language: python
cache: pip


before_install:
- python --version
- pip install -U pip

#needed for test stage
- pip install -U pytest-cov
- pip install codecov

#needed for deployment stage
- pip install --upgrade build
- pip install --upgrade twine

install:
- pip install -r requirements.txt
- pip install ".[test]" .  #install package + test dependencies  


jobs:
  include:
    - stage: test
      script:
      - echo 'Execute Python Tests'
      - pytest --cov-report term --cov=./ tests      
      - echo 'Python Tests completed'
      after_script:
      - bash <(curl -s https://codecov.io/bash) # submit coverage,whatever we have failure or success
    - stage: deploy    
      script: skip
      deploy:
        provider: pypi
        username: "__token__"
        password: $PTEST_PIPY_PWD
        distributions: "sdist bdist_wheel"
        server: https://test.pypi.org/legacy/
        on:
          branch: main

