language: python
cache: pip

env:
  global:
    secure: DtS6RHZIYCWiGemL8l2YrRoRRDSreSR8m2xIj+aTa9rUBX5TY79Jnf+eFQChs6nZVRu3XEPsM2QqO1UgwV3gKuwHePbczVwDM4bq5edteuQ+s581ce1RzjuFpFyHO8rqUXT6EwD8Ig4ZD27VtGWdgDpvDVOJFdpSgb8yT84zlVfM7M3ke2GayUT0PCVEYTr/5BWinRfr49Qdk2+OsMcdbKBcW3rsJXr7CYYfbvcBpyxfvlt34ToK5qgenrAP5e3cpglaUr7M2ExRMantDsqWycXZkOLFlEAARhFyo3EHBgdLBX8BOMoQVLL39uQ9BqeHb4xHQzmO47DxFxpBzBR7gAP3lSjqOKp3Y6yBpeoOqJJzolE36Qxyi4q4tbbxdV/5K8L5pWY4TIxTg3+B+zGU/ADBq7ImSTBWLrTZ9JkUFobxSX1u90vYS8C1twNekoUQ29aXfqfRyS90gx3xJW5ZC5voMeSt1SR2h7eNtLUi3MKr4YvUu7GbW0X10ruPK52KefbsiYKp8snsbLMgDWCqDMfEDQsC2mnu2TL5frxnVKUOG/HhvXcfCOpMKQTq0Jsy+IqGDJ5DlwvZuMt95xM1WcLnSaj/KR/i8VJX7kv4xfRT9q6ocGi/Q6+9q5r1eKJj1QAvek4h/p/V17m1U0Be34R7xkQ1ftXFGahT69FXtwQ=


before_install:
- python --version
- pip install -U pip

#needed for test stage
- pip install -U pytest-cov
- pip install codecov

#needed for deployment stage
- pip install --upgrade build
- pip install --upgrade twine

install:
- pip install -r requirements.txt
- pip install ".[test]" .

jobs:
  include:
    - stage: test
      script:
      - echo 'Execute Python Tests'
      - pytest --cov-report term --cov=./ tests
      after_script:
      - bash <(curl -s https://codecov.io/bash) # submit coverage,whatever we have failure or success
    - stage: build
      script:
      - python3 -m build
    - stage: deploy    
        provider: pypi
        username: "__token__"
        password:
          secure: env(secure)
        server: https://test.pypi.org/legacy/

stages:
- name: test
  if: type = pull_request
- name: build
  if: type = push AND branch = master  
- name: deploy
  if: type = push AND branch = master
