---
- name: Configure docker being root user
  hosts: ec2
  become : yes
  tasks:
  - name: install docker
    yum:    
        name: docker
        state: latest
        update_cache: yes
  - name: Make sure docker is started
    service:
        name: docker
        state: started
  - name: Update group for ec2-user to launch docker containers
    shell: |              
       group add docker
       usermod -aG docker ec2-user               
  - name: Reconnect to server session so group is taken into account
    ansible.builtin.meta: reset_connection


- name: Make sure ec2-user can run docker commands
  hosts: ec2
  tasks:
  - name: run docker ps command
    command : docker ps
    register: docker_result  
  - ansible.builtin.debug: msg={{docker_result.stdout}}
