---
- name: Configure docker
  hosts: ec2
  tasks:
  - name: install docker
    yum:    
        name: docker
        state: latest
  - name: start docker
    service:
        name: docker
        state: started
  - name: Update group for ec2-user to launch docker containers
    shell: |              
       group add docker
       usermod -aG docker ec2-user               
